---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: sync_dev_secrets
  pull: always
  image: quay.io/ukhomeofficedigital/cop-secrets
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: DEV_DRONE_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: DEV_DRONE_AWS_SECRET_ACCESS_KEY
    DEPLOY_ENV: dev
    DRONE_SERVER: https://drone-gh.acp.homeoffice.gov.uk
    DRONE_TOKEN:
      from_secret: DRONE_V1_PUBLIC_TOKEN
    DRONE_VERSION: ${DRONE_SYSTEM_VERSION}
  when:
    branch:
    - master
    event:
    - push

- name: sync_staging_secrets
  pull: always
  image: quay.io/ukhomeofficedigital/cop-secrets
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: STAGING_DRONE_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: STAGING_DRONE_AWS_SECRET_ACCESS_KEY
    DEPLOY_ENV: staging
    DRONE_SERVER: https://drone-gh.acp.homeoffice.gov.uk
    DRONE_TOKEN:
      from_secret: DRONE_V1_PUBLIC_TOKEN
    DRONE_VERSION: ${DRONE_SYSTEM_VERSION}
  when:
    event:
    - promote
    target:
    - staging

- name: sync_production_secrets
  pull: always
  image: quay.io/ukhomeofficedigital/cop-secrets
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: PRODUCTION_DRONE_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: PRODUCTION_DRONE_AWS_SECRET_ACCESS_KEY
    DEPLOY_ENV: production
    DRONE_SERVER: https://drone-gh.acp.homeoffice.gov.uk
    DRONE_TOKEN:
      from_secret: DRONE_V1_PUBLIC_TOKEN
    DRONE_VERSION: ${DRONE_SYSTEM_VERSION}
  when:
    event:
    - promote
    target:
    - production

- name: deploy_to_dev
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/helm:latest
  commands:
  - /run-helm.sh list -n cms-dev
  - helm upgrade --install cms-clamav ./charts/clamav/ -f ./charts/clamav/values.yaml -n cms-dev
  environment:
    KUBE_CERTIFICATE_AUTHORITY_DATA:
      from_secret: DEV_KUBE_CA_DATA
    KUBE_CLUSTER_NAME:
      from_secret: DEV_KUBE_CLUSTER_NAME
    KUBE_SERVER:
      from_secret: DEV_KUBE_SERVER
    KUBE_TOKEN:
      from_secret: DEV_KUBE_TOKEN
  when:
    branch:
    - master
    event:
    - push

- name: deploy_to_staging
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/helm:latest
  commands:
  - /run-helm.sh list -n cms-sit
  - helm upgrade --install cms-clamav ./charts/clamav/ -f ./charts/clamav/values.yaml -n cms-sit
  environment:
    KUBE_CERTIFICATE_AUTHORITY_DATA:
      from_secret: SIT_KUBE_CA_DATA
    KUBE_CLUSTER_NAME:
      from_secret: SIT_KUBE_CLUSTER_NAME
    KUBE_SERVER:
      from_secret: SIT_KUBE_SERVER
    KUBE_TOKEN:
      from_secret: SIT_KUBE_TOKEN
  when:
    event:
    - promote
    target:
    - sit

- name: deploy_to_staging
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/helm:latest
  commands:
  - /run-helm.sh list -n cms-staging
  - helm upgrade --install cms-clamav ./charts/clamav/ -f ./charts/clamav/values.yaml -n cms-staging
  environment:
    KUBE_CERTIFICATE_AUTHORITY_DATA:
      from_secret: STAGING_KUBE_CA_DATA
    KUBE_CLUSTER_NAME:
      from_secret: STAGING_KUBE_CLUSTER_NAME
    KUBE_SERVER:
      from_secret: STAGING_KUBE_SERVER
    KUBE_TOKEN:
      from_secret: STAGING_KUBE_TOKEN
  when:
    event:
    - promote
    target:
    - staging

- name: deploy_to_production
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/helm:latest
  commands:
  - /run-helm.sh list -n cms-prod
  - helm upgrade --install cms-clamav ./charts/clamav/ -f ./charts/clamav/values.yaml -n cms-prod
  environment:
    KUBE_CERTIFICATE_AUTHORITY_DATA:
      from_secret: PRODUCTION_KUBE_CA_DATA
    KUBE_CLUSTER_NAME:
      from_secret: PRODUCTION_KUBE_CLUSTER_NAME
    KUBE_SERVER:
      from_secret: PRODUCTION_KUBE_SERVER
    KUBE_TOKEN:
      from_secret: PRODUCTION_KUBE_TOKEN
  when:
    event:
    - promote
    target:
    - production

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

- name: anchore-submission-server
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  pull: always
  commands:
    - /run.sh server
...
